baseURL = 'https://ilesec.github.io/'
languageCode = 'en-us'
title = 'Ilkka Hyvönen´s site'
theme = 'blowfish'
[params.author]
name = "Ilkka Hyvönen"
image = "img/author.jpg"
headline = "Security Architect"
bio = "Cloud Solution Architect at Microsoft"
[caches]
  [caches.images]
    dir = ':cacheDir/images'