[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "/About"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/ilesec/"
  weight = 30

[[main]]
  pre = "LinkedIn"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ilkkahyvonen/"
  weight = 30

